### ISSUE TITLE
Add `sql-query` command

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/b#129] opened 2021-03-02 23:33 UTC
The drush SQL commands would also be really nice. Commands and their drush aliases are:

sql-query (sql:query), most especially; but also

sql-cli (sqlc, sql:cli)
sql-connect (sql:connect)
sql-create (sql:create)
sql-drop (sql:drop)
sql-dump (sql:dump)
sql-sync

**Comment by alanmels** [comment] 2021-03-03 01:25
As promised in today's VUG you can assign this task to me. AltaGrade team will roll out all database-related features. But because of current workload, I think we will need couple weeks to get back to this. If someone would like to take a stab before that, then you are more than welcome.

**Comment by alanmels** [comment] 2021-04-03 07:16
Not all the database commands, but three following new commands have been introduced by the PR:

```
bee sql-drop
bee sql-dump
bee sql-cli
```

**Comment by klonos** [comment] 2021-10-29 14:52
Can we please also add aliases using `db-` instead of `sql-`?

I also like `db-import` (`dbim`?) and `db-export` (`dbex`?) better, as mentioned in #113.

**Comment by ghost** [comment] 2021-11-01 10:04
Closed https://github.com/backdrop-contrib/bee/issues/113 as a duplicate of this issue. That one just mentioned:

> Lando has `db-import` and `db-export` commands. I'd like to add similar commands to `bee`.

**Comment by ghost** [comment] 2021-11-02 05:35
Adding my work-in-progress PR here (so I don't lose it).

**Comment by ghost** [comment] 2021-11-03 10:34
The PR adds the following commands:
- 'db-export' (aka 'dbex', 'db-dump', 'sql-export', 'sql-dump')
- 'db-import' (aka 'dbim', 'sql-import')
- 'sql' (aka 'sqlc', 'sql-cli', 'db-cli')

I figure these would be the most popular, especially considering 'sql' allows you to do lots of the other things (like creating or dropping databases, albeit not as succinctly). I'm not going to add 'sql-sync' (at least in the near future) as this would require a lot of other work in Bee to function.

**Comment by laryn** [comment] 2021-11-10 20:33
Just tested with `lando bee sql < backdrop-ready.sql` and it worked flawlessly. 👍  

First time `bee` user but it feels really clean and fresh! (Tested a few of my favourites without knowing if they'd work -- `dl` `en` etc -- and was pleasantly surprised). Good work.

**Comment by bugfolder** [comment] 2021-11-19 00:20
Tested `bee sql` and `bee db-export ...` and both worked as advertised. 👍

**Comment by ghost** [comment] 2021-11-19 01:36
Thanks guys, merged.

**Closed as completed** 2021-11-19 01:36 UTC
