### ISSUE TITLE
'core-status' should display more info

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#84] opened 2019-10-23 18:08 UTC
Currently, the `core-status` command displays the following information about a Backdrop site:

```
 Backdrop CMS
 Backdrop root
 Database driver
 Database host
 Database name
 Database username
```

Here's the equivalent info from a Drupal site with Drush:

```
Drupal version
Site URI
Database driver
Database hostname
Database username
Database name
Database
Drupal bootstrap
Drupal user
Default theme
Administration theme
PHP configuration
PHP OS
Drush script
Drush version
Drush temp directory
Drush configuration
Drush alias files
Install profile
Drupal root
Drupal Settings File
Site path
File directory path
Temporary file directory path
```

I think we can add a bit more info to `b`...

**Comment by ghost** [comment] 2019-10-23 18:11
Also, here's the info from the same Drupal installation as above, but run from outside of the site directory (i.e. the above was run from within the site dir):

```
Drupal version
PHP configuration
PHP OS
Drush script
Drush version
Drush temp directory
Drush configuration
Drush alias files
Drupal root
Drupal Settings File
```

Much less info (because the site-specific info isn't available), but it still gives generic Drupal info at least.

In Backdrop no info is given at all outside a site directory. I'm sure we can improve that too.

**Comment by indigoxela** [comment] 2019-10-25 10:53
I started to enhance "b st".

What other information could be interesting?

**Comment by ghost** [comment] 2020-01-20 07:59
I think https://github.com/backdrop-contrib/b/issues/96 will be handy here as then we'll know when to provide information about the site itself (as opposed to generic Backdrop info).

**Comment by indigoxela** [comment] 2020-01-20 12:12
> I think #96 will be handy here

I agree. And we could probably grab interesting states info (via state_get()).
For instance update_last_check or install_time.

**Comment by indigoxela** [comment] 2021-02-02 08:07
I'll close my PR as I see no chance that it can get merged.

**Comment by klonos** [comment] 2022-10-18 03:04
@indigoxela care to elaborate on your last comment here please? Are you frustrated that it took long for people to review your code and provide feedback, or have things changed that your PR does no longer apply.

Regardless, and as general feedback on this thread, I think that at the very minimum we should be reporting php version (which is what drove me here TBH) and bee version.

Also, I don't see any real value in this line of the output:
```
Database password   ********** 
```

**Comment by indigoxela** [comment] 2022-10-18 07:34
@klonos there wasn't much interest for more than two years, and now the patch doesn't apply anymore, anyway.

>  I think that at the very minimum we should be reporting php version (which is what drove me here TBH) and bee version.

```
    $rows[] = array(
      array('value' => bt('PHP version')),
      array('value' => PHP_VERSION),
    );
```

I don't think that bee has versions, yet.

**Comment by indigoxela** [comment] 2022-10-18 09:01
Here we go, yet another PR: #219

Sample output:
```
 Backdrop CMS           1.23.0                               
 Root directory         /var/www/crashburn/html              
 Site type              Single                               
 Database               mysql                                
 Database name          bd_crashburn                         
 Database username      bd_crashburn                         
 Database password      **********                           
 Database host          127.0.0.1                            
 Database port                                               
 Cron last run          2022-10-20 09:48:01 CEST             
 Install time           2022-07-21 10:14:28 CEST             
 Maintenance mode       off                                  
 Update last check      2022-10-19 19:48:06 CEST             
 Settings.php path      /var/www/crashburn/html/settings.php 
 Drupal compatibility   on                                   
 Config dir active      /var/www/crashburn/bd-config/active  
 Config dir staging     /var/www/crashburn/bd-config/staging 
 Site name              My crashburn site                   
 Default theme          basis                                
 Admin theme            seven                                
 Public files path      /var/www/crashburn/html/files        
 Private files path     /var/www/crashburn/privatefiles      
 Temporary files path   /tmp                                 
 Preprocess CSS         on                                   
 Preprocess JS          off                                  
 Theme debug            off                                  
 Error display level    all                                  
 PHP cli version        8.1.11                               
 PHP ini path           /etc/php/8.1/cli/php.ini
```
^^ we triple the information. :wink:

**Comment by indigoxela** [comment] 2022-10-18 14:25
> Also, I don't see any real value in this line of the output:

@klonos that's hidden by default for security reasons, you can display the pw value with a param `bee st --show-password`

**Comment by yorkshire-pudding** [comment] 2022-10-18 14:49
Thanks @indigoxela - this looks great.  I think the `bee_format_date` helper function is a sensible extra that enhances this and is available to use elsewhere.
Bee version - there is a separate issue for this (#203) and it would probably make sense to add in here when we start doing releases (@ElusiveMind - FYI)
One suggestion I have is `theme_debug`; it would probably make sense near preprocess CSS or underneath the themes but open to other suggestions.

Just wondering, is it mostly the case that PHP CLI is the same version as the web version.  Are there many places where they might be different and if so, would it be possible to get the PHP version in use on the web front end?

**Comment by indigoxela** [comment] 2022-10-18 15:04
> I think the bee_format_date helper function is a sensible extra...

Phew... I wasn't 100% sure, if that's the case (would have reverted it to inline code then). :smile:

> One suggestion I have is theme_debug...

I've just added that... after a little head scratching I put it near error_display - I think these both are settings you wouldn't want to be turned on on production sites. But we can move that around as needed.

> is it mostly the case that PHP CLI is the same version as the web version...

Not really, but I don't know of any trick to get the http information from command line (drush doesn't do that, either - also displays cli). Via web frontend the php version should *never* be exposed. If your hoster does somehow - switch hosting. :grin:

**Comment by yorkshire-pudding** [comment] 2022-10-19 09:01
Thanks @indigoxela  - this looks really good. @klonos - any further thoughts?

**Comment by indigoxela** [comment] 2022-10-19 11:19
Some Office Hours outcome:

- We show absolute paths (our conclusion: that's OK) (`/path/to/private/files` instead of `../files`). That's easier to understand, especially when running bee from outside the install
- More feedback re the new bee_format_date() helper function would be great. What's the output on your dev? (We already had a Debian Linux and a Lando output example.)

Note: The intention of the new helper is to require no bootstrap level at all to display a timestamp in a readable way - the B format_date() function would require us to raise the bootstrap level for the status command (and that makes no sense for just outputting a date).

More feedback on the values and eventually redundant or missing info would be cool, too. That could eventually go into a follow-up for quicker progress.

**Comment by indigoxela** [comment] 2022-10-20 07:17
Oh, dang, back to "needs work" - I just realized that reading only the config isn't sufficient, as that ignores overridden values from settings.php. So we have to raise the bootstrap level.

**Comment by yorkshire-pudding** [comment] 2022-10-20 08:15
Well spotted @indigoxela - I hadn't thought of that.

**Comment by indigoxela** [comment] 2022-10-20 08:39
Fixed. I verified with an overridden "site_name" value in settings.php.

Raising the bootstrap level is counter-productive, as we end up with empty settings - we ran into that problem [before](https://github.com/backdrop-contrib/bee/issues/61#issuecomment-810124197). It's caused by the require_**once** in core's backdrop_settings_initialize().

**Comment by yorkshire-pudding** [comment] 2022-10-21 09:25
Thanks @indigoxela - I've tested and it works with config override.  I'm looked at the code, but I can't quite work out which bit is doing this clever bit.  For my benefit (not that there is anything wrong, just I don't fully understand it), please can you point to the relevant bits and explain how it's doing it?

**Comment by indigoxela** [comment] 2022-10-21 09:39
> ... can you point to the relevant bits and explain how it's doing it?

Instead of manually including settings.php, I switched to `global $settings, $config_directories;`, as backdrop_settings_initialize() has already run (see includes/miscellaneous.inc / bee_initialize_console()).

The way I did it before (not using the globals, but including settings.php) war wrong, as it didn't properly initialize the overridden values (all config values can be overridden via settings.php).

**Comment by yorkshire-pudding** [comment] 2022-10-21 13:23
Thank you @indigoxela - this is a really great improvement to the usefulness of this function.

**Closed as completed** 2022-10-21 13:23 UTC
