### ISSUE TITLE
Error PHP 8.1 Passing null to parameter #2 ($string) of type string is deprecated download.bee.inc:200

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/b#213] opened 2022-10-05 15:48 UTC
**Steps to reproduce**

1. Set Bee lando file to PHP 8.1
2. run `lando start`
3. run `lando run-tests`

**Expected result**
All tests pass

**Actual result**
Some tests fail

<details>
<summary>Test Results</summary>

```bash
PHPUnit 8.5.30 #StandWithUkraine

Bee Core
 ✔ Bee is installed correctly
 ✔ Unknown command triggers an error
 ✔ Missing required argument triggers an error
 ✔ Commands can be called via an alias
 ✔ Root global option works
 ✔ Yes global option works
 ✔ Debug global option works

Cache Commands
 ✔ Cache clear command works

Config Commands
 ✔ Config get command works
 ✔ Config set command works
 ✔ Config export command works
 ✔ Config import command works

Cron Commands
 ✔ Cron command works

DBCommands
 ✔ Db export command works
 ✔ Db import command works

DBLog Commands
 ✔ Log command works

Download Commands
 ✔ Download command works
 ✔ Download core command works

Help Commands
 ✔ Help command works

PHPCommands
 ✔ Eval command works

Projects Commands
 ✔ Projects command works
 ✔ Enable command works
 ✔ Disable command works
 ✔ Uninstall command works
 ✔ Theme default command works
 ✔ Theme admin command works

Update Commands
 ✔ Update db command works

User Commands
 ✔ Users command works
 ✔ User password command works
 ✔ User login command works

Time: 39.35 seconds, Memory: 15.07 MB

OK (30 tests, 89 assertions)
PHPUnit 8.5.30 #StandWithUkraine

Multisite
 ✔ Site global option works

Multisite Install Commands
 ✔ Install command works
curl: (6) Could not resolve host: api.github.com

Multisite Download Commands
 ✘ Download command works
   ┐
   ├ Failed asserting that 'explode(): Passing null to parameter #2 ($string) of type string is deprecated\n
   ├  /app/commands/download.bee.inc:200\n
   ├ \n
   ├ \n
   ├  [✘] The 'type' of project 'lumi' could not be determined. \n
   ├ \n
   ├ ' contains "'lumi' was downloaded into '/app/multisite/sites/multi_one/themes/lumi'.".
   │
   ╵ /app/tests/multisite/MultisiteDownloadCommandsTest.php:22
   ┴

Time: 14.46 seconds, Memory: 13.07 MB

Summary of non-successful tests:

Multisite Download Commands
 ✘ Download command works
   ┐
   ├ Failed asserting that 'explode(): Passing null to parameter #2 ($string) of type string is deprecated\n
   ├  /app/commands/download.bee.inc:200\n
   ├ \n
   ├ \n
   ├  [✘] The 'type' of project 'lumi' could not be determined. \n
   ├ \n
   ├ ' contains "'lumi' was downloaded into '/app/multisite/sites/multi_one/themes/lumi'.".
   │
   ╵ /app/tests/multisite/MultisiteDownloadCommandsTest.php:22
   ┴

FAILURES!
Tests: 3, Assertions: 17, Failures: 1.
```
</details>

**Comment by yorkshire-pudding** [comment] 2022-10-05 16:19
Ran again and all fine.  Turns out this was a temporary issue with accessing github:

>curl: (6) Could not resolve host: api.github.com

**Comment by yorkshire-pudding** [comment] 2022-10-05 16:36
While it is working again, if there is an issue with github then it causes issues including the aforementioned deprecated notice

**Comment by yorkshire-pudding** [comment] 2022-10-06 11:33
Got another one today:

```
substr(): Passing null to parameter #1 ($string) of type string is deprecated
 /usr/local/bin/bee/commands/download.bee.inc:179
```

**Comment by indigoxela** [comment] 2022-10-24 12:31
@yorkshire-pudding I'm sure we could catch that symptom (deprecation warning), but we can't catch the base problem in Bee.

If resolving DNS records doesn't work, the test run will fail. `Could not resolve host: api.github.com` - there's nothing we can do at that point to finish the test.

Or did you ever see that problem when doing a real download?

**Comment by yorkshire-pudding** [comment] 2022-10-24 12:47
@indigoxela - I was just thinking of treating the deprecation warning rather than the underlying issue which is intermittent, and not predictable.  I seem to get it quite often if I try to download several in a one liner `bee dl module_one module two ... ` type command so I was wondering if it is a form of throttling.  I get this on 7.4 also, so its not an 8.1 issue, just the deprecation warning is the deprecation issue.  I have been planning to do it, but just not got round to it yet

**Comment by indigoxela** [comment] 2022-10-24 13:01
>  I seem to get it quite often if I try to download several in a one liner

Ah, I get it - actually two different topics.

>  I seem to get it quite often if I try to download several in a one liner 

It might help to post examples here, as I never ran into that.

```
  $headers = get_headers($url);
  $response = substr($headers[0], 9, 3);
```
I wonder what goes so wrong with your download(s), that get_headers() ends up with FALSE. :thinking:

**Comment by yorkshire-pudding** [comment] 2022-10-24 13:10
@indigoxela - I suspect it could be a lando thing.  I run lando on Ubuntu inside Windows Subsystem for Linux (WSL2) on Windows 10.  I might try replicating on my hosting where lando isn't a factor.

**Comment by indigoxela** [comment] 2022-10-26 14:39
> I suspect it could be a lando thing...

FWIW, here's a PR: #229

We need someone to test and/or even confirm the problem, as I couldn't reproduce it at all.

Idea behind my PR: yes, get_headers() can return FALSE on error, so let's not assume it's always an array of strings. :grin:

**Comment by yorkshire-pudding** [comment] 2022-10-31 08:38
Thanks @indigoxela - I've tested this, recreated the error on my system and then confirmed that the PR removes the deprecation notice.

**Closed as completed** 2022-10-31 08:42 UTC
