### ISSUE TITLE
Add login/password reset command

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/b#61] opened 2019-10-16 18:19 UTC
It'd be nice to have a login/password reset command (like Drush's `uli`) for those times where you run the automatic install but forget to note down the generated admin password :roll_eyes:

**Comment by indigoxela** [comment] 2019-10-28 11:41
More convenient than a reset link is to directly reset a password for a given username.

<strike>Help text is still missing.</strike> Wording might need improvement.

Bonus feature of my PR : list all users.

https://github.com/backdrop-contrib/b/pull/88

Usage examples:
```
b uls
b upw theusername
b upw theusername --password=supersecret
```

**Comment by indigoxela** [comment] 2020-10-29 14:34
Hey, glad to see some activity here with "b".

@BWPanda I wonder if you're still interested in this addition or a variant of it - some user related commands.

**Comment by alanmels** [comment] 2020-10-29 18:05
Guys, as I tried to explain on https://forum.backdropcms.org/forum/brush-command-line-shell-and-unix-scripting-interface-backdrop-cms I still believe, that as a project with clean code `b` should be a preferable command line tool for Backdrop in long run. I hope one day when `b` is mature enough we'll totally switch to it. Until then, just for information of everybody interested:

In order to have most of commands to start working for Backdrop ASAP, we've refactored pre-Symfony `drush` into what is now [brush](https://github.com/backdrop-contrib/brush) and have been already enjoying the easiness of brushing Backdrop project from command line, including use of that kind of commands like `brush uli`. All of the `sql` related (`brush sql-dump`, `brush sql-drop`, `brush sql-cli`, `brush sql-query`) commands also are fully functional.

**Comment by ghost** [comment] 2020-10-29 19:53
@indigoxela Yep, still interested. However all of my effort is currently on refactoring the code. Once that's done I'll focus on the other issues in the 1.x milestone so we can get an initial, stable version released. Only then will I get to other issues like this one.

Sorry for the delay, but I'm back working on this after a bit of a hiatus and look forward to getting it ready and released.

@alanmels Yep, looking forward to a stable release so we can get more community interest and feedback.

**Comment by oadaeh** [comment] 2020-10-30 16:09
It seems like it would be a good idea to merge the two efforts of `b` and `brush` to achieve a solution that is not dependent on `drush` sooner.

**Comment by alanmels** [comment] 2020-10-30 18:56
> It seems like it would be a good idea to merge the two efforts of `b` and `brush` to achieve a solution that is not dependent on `drush` sooner.

I don't mind merging two projects, however so everybody has clear understanding of the differences of two projects:

- The main reason why we had decided to refactor `drush` into `brush` was the fact that both `b` and [Drush Integration for Backdrop CMS](https://github.com/backdrop-contrib/backdrop-drush-extension) were (in fact still are) lacking some commands which we badly needed for automation of our development processes. 

- While we've got almost all `drush` commands working on `brush`, it's code base has lot's of unnecessary Drupal leftovers that are not relevant for Backdrop anymore. However, since the main goal of AltaGrade team was to just get most commands functional, we never spent our time cleaning the code. 

- I personally do like that `b` has clean code that eventually could grow into gaining more functionality. And I am not sure if merging two projects (one with lot's of unnecessary load of code and the other with a clean code) into each other is a good idea. However, I believe that could be possible only in two following scenarios:

(1) We could keep `b` clean and just import only needed and already working parts of code from `brush`. We've got almost all commands already working on `brush` and I am totally ok if we start just copying only needed functions from `brush` into `b`.

(2) Another possible way, if we all switch to `brush` and start helping each other to get rid of all unnecessary part of the code-base. Since `brush` is already functional, we could just gradually get rid of all parts of `brush` code-base we don't need for Backdrop.

I am not sure which one is more preferable to the community, so I'll leave this for the Backdrop community to decide.

**Comment by ghost** [comment] 2020-10-30 19:50
Let's not derail this issue with general discussions about the project overall. Just know that I am actively working on a stable v1 of `b` and once that's out we can talk about whether there's interest in merging brush functionality in.

**Comment by indigoxela** [comment] 2021-02-02 08:06
I'll close my related PR for now. Not sure if it could get merged anyway, after the code rewrite.

The PR has been around since October 2019 - I think it's time to accept that it will never get merged. :wink: I'll leave the issue open, though. It's still relevant.

**Comment by ghost** [comment] 2021-02-02 09:08
> The PR has been around since October 2019 - I think it's time to accept that it will never get merged.

Sorry. I've been (on and off) rewriting the code for the last 12 months, so wanted to get that done before looking at new functionality. Definitely something that should be added though. You're welcome to submit a new/updated PR based on the refactored code. There's a new [API.md file](https://github.com/backdrop-contrib/b/blob/1.x-1.x/API.md) that may be helpful...

**Comment by stpaultim** [comment] 2021-02-24 23:16
Yes, I'm just trying B for the first time and this was one of the first commands that I went looking for. It is by far the most common thing I use Drush for, I am not a drush power user. 

I would like to use b a lot more than I used to use drush and I've love to get this feature. 

Will be watching to see how I can help.

**Comment by ghost** [comment] 2021-03-22 01:59
Since this is such popular functionality, let's add it for v1.0...

**Comment by ghost** [comment] 2021-03-23 11:28
Inspired by @indigoxela's previous PR, I made this new one that:

- Displays a list of all users
- Lets you reset a user's password
- Displays the login link for a user

https://github.com/backdrop-contrib/bee/pull/149

Still need to add tests though.

**Comment by ghost** [comment] 2021-03-24 05:31
PR updated with tests. Care to review @indigoxela?

**Comment by indigoxela** [comment] 2021-03-27 14:36
The users (uls, user-list) command works fine :+1:

The user-password (upw, upwd) command works fine, too :+1:

The user-login command does not provide a proper login link:

1. The base url is missing, so the output link ends up to be something like `http://html/de/user/reset/1/1616855143/ve8C...IIe_gG6YA/login`
2. The link, even if corrected leads to a password reset form instead of logging in with following message displayed: `You have tried to use a reset password link that has either been used or is no longer valid. Please request a new one using the form below. `

So "user-login" still needs some work.

Update: it's the check for $hashed_pass that fails (row 152 in core/modules/user/user.pages.inc). Not sure why.

**Comment by ghost** [comment] 2021-03-27 20:01
Thanks for the review @indigoxela.

1. I noticed that too, but when I tried running the same command in Drush for the same site, it did the same thing. So I'd be interested to know how to fix this, considering it seems even Drush hasn't/couldn't...

2. I'll take a look.

**Comment by alanmels** [comment] 2021-03-27 20:26
Drush (and Brush too) add base url to the generated one-time password link only if `$base_url` is set in settings.php. Otherwise, it replaces the domain name with `default` like so:

```
http://default/user/reset/1/1616876684/hN3lx06dkidL13tOY6a4cprRUZeSb5k0yuu2hrcysO4/login
```

**Comment by indigoxela** [comment] 2021-03-28 08:59
I did realize, too, that drush (also for Drupal) outputs that weird link - I don't think that this means that outputting an url like that is OK. :wink: 

But the main problem is, that the login link does not work, because the rehashed password doesn't validate - this is something that does work properly with drush.

Or have you both been able to actually login with that link? I tried with several different Backdrop installs, I always get redirected to the password reset form with the message `You have tried to use a reset password link...` as posted in my previous comment.

**Comment by ghost** [comment] 2021-03-28 09:13
I can confirm that setting the base_url in settings.php produces a valid link. Unless anyone can provide a better solution, I'm happy with that as a workaround for now.

As for the link not actually working, I could also reproduce that and am currently looking into it (its been a busy day though)...

**Comment by ghost** [comment] 2021-03-28 10:47
For the life of me, I can't figure this out. The Drush command works fine, while Bee's doesn't. I don't see any obvious differences between the two generated URLs (apart from what's supposed to be different (the timestamp and hash)).

Help...?

**Comment by indigoxela** [comment] 2021-03-28 10:50
> For the life of me, I can't figure this out.

Same here, or actually worse... how can this ever work in drush? The logic inside function user_pass_reset() should also prevent drush's urls from working. But they *do* work.

**Comment by indigoxela** [comment] 2021-03-28 14:11
It's about the hash salt...

Further down the road it's attempted to access the hash_salt with backdrop_get_hash_salt() - in turn `settings_get('hash_salt');`, which is always NULL, so a new hash gets generated on-the-fly, which will never match the value, the validation will use.

The problem is that the globals from $settings aren't available, so settings_get() always returns NULL. Weird, because I thought that backdrop_settings_initialize() would take care of that. That's obviously not as I assumed.

@BWPanda happy further digging. :smile: 

Quick and dirty for debugging in function user_login_bee_callback():
```
  // this should happen somewhere else...
  global $settings;
  include BACKDROP_ROOT . '/' . conf_path() . '/settings.php';
  var_dump($settings);
```

**Comment by ghost** [comment] 2021-03-29 04:09
@indigoxela I cannot reproduce the NULL hash_salt thing you mentioned. Mine is always populated, but the login link still doesn't work...

I thought maybe the issue with the login link is because of a difference between the Drush environment and Bee's environment, so I output and compared all values of `$_SERVER` for Drush and Bee. There were some differences between Drush and Bee, but when I changed Bee's values to match Drush's, the login link *still* didn't work...

This is very frustrating.

**Comment by indigoxela** [comment] 2021-03-29 07:06
Strange... I was able to use the login links when inserting above code *before* user_pass_reset_url() - order matters.
Only then the actual hash_salt from the settings file was available. I tested with both, single site and multisite.

Otherwise backdrop_get_hash_salt() returned the fallback salt - which causes the validation in user_pass_reset() to fail.

Note: you always get a hash_salt, but it might not be the right one (from settings.php) - that causes the validation problem.

**Comment by ghost** [comment] 2021-03-29 22:07
Thanks @indigoxela! I'm still not 100% sure why, but that seems to work 😃 I've updated the PR.

**Comment by indigoxela** [comment] 2021-03-30 06:26
> I'm still not 100% sure why, but that seems to work

I'd really like to understand that better. If $settings are not available in the user commands, they might also be missing in other commands that need them. Should they always be available?

**Comment by indigoxela** [comment] 2021-03-30 10:54
The base problem is that - depending on the command and its required bootstrap level - backdrop_settings_initialize() runs twice per request.

Looking at core function backdrop_settings_initialize():
```
...
  $conf = array();
  $settings = array();
...
  if (file_exists($conf_path . '/settings.php')) {
    require_once $conf_path . '/settings.php';
  }
```
See the "require_**once**"? The second run of backdrop_settings_initialize() resets $settings to an empty array, but as settings.php has already been included, that won't happen again, so we end up with an empty $settings array.

Verify the double run by adding following in core/includes/bootstrap.inc in function backdrop_settings_initialize():
```
  $foo = debug_backtrace();
  var_dump($foo);
```

Then run a command that requires the full bootstrap level like `bee users`.

Inspect both backtraces - backdrop_settings_initialize() has been run by bee_initialize_console() AND by bee_process_command().

The full lists:

- bee_initialize_console
- backdrop_settings_initialize

and:

- bee_process_command
- bee_bootstrap
- backdrop_bootstrap
- _backdrop_bootstrap_configuration
- backdrop_settings_initialize

Note that drush doesn't have that problem. Even with high-bootstrap-level commands, backdrop_settings_initialize() is only run once. That's why drush has no problem with the fallback hash_salt breaking the login link verification.

I have to admit, that I don't know bee good enough to be able to suggest a solution.

**Comment by ghost** [comment] 2021-03-30 10:57
@indigoxela Wow, you're good! Thanks for that. I'd have never figured all that out! 😄 I'll have to think about how to address this...

**Closed as completed** 2021-06-26 02:36 UTC

**Comment by ghost** [comment] 2021-06-26 02:37
Since I couldn't work out how to address this in a better way, I figured better just to merge the working code we have and let people actually start using the new commands. If this issue comes up again in future, we can look at it again then.

**Comment by indigoxela** [comment] 2021-06-26 09:21
> I figured better just to merge the working code we have and let people actually start using the new commands

That's understood. I suspect, to do a super-clean solution, a bigger change might be needed. Possibly bee has to take over the whole initialize part to overcome that require_once limitation by core.

**Comment by olafgrabienski** [comment] 2023-03-26 20:31
From https://github.com/backdrop-contrib/bee/issues/61#issuecomment-808742764:
> The user-login command does not provide a proper login link:
>
> 1. The base url is missing, so the output link ends up to be something like `http://html/de/user/reset/1/1616855143/ve8C...IIe_gG6YA/login`

I'm currently testing *Bee* and just stumbled upon the behavior of the `user-login` command as described above. If I understand the issue correctly, it can't be fixed (easily). What do you all think of documenting the limitation then – I mean, not only in the Wiki but also as a hint when people run the command? Something along the lines that the URL is only supposed to be correct if there is a Base URL in `settings.php`.

**Comment by yorkshire-pudding** [comment] 2023-03-27 07:52
@olafgrabienski - I think this issue will help:
https://github.com/backdrop-contrib/bee/issues/195

I've just agreed with @quicksketch that I can take over this PR to get it over the line.

I agree it makes sense to modify the wiki, but hold off on the command hint until we get this in.

**Comment by olafgrabienski** [comment] 2023-03-27 09:12
@yorkshire-pudding Thanks for the link, indeed I hadn't seen that issue. Makes sense to hold off on the command hint.

**Comment by yorkshire-pudding** [comment] 2023-03-29 11:21
@olafgrabienski - the hint has been added into bee.  I'll update the wiki
