### ISSUE TITLE
Allow optional additional arguments to be used with db-export

### ISSUE THREAD

**Issue by ElusiveMind** [backdrop-contrib/b#208] opened 2022-10-02 00:01 UTC
When using MariaDB 10.7:

Server version: 5.5.5-10.7.6-MariaDB-1:10.7.6+maria~ubu2004 mariadb.org binary distribution

I am getting the following error when trying to db-export:

```
root@fe35f37cfb75:/var/www/html/web# bee db-export 
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'backdrop' AND TABLE_NAME = 'batch';': Unknown table 'column_statistics' in information_schema (1109)
```

It is possible to bypass this with drush by adding the following parameters to the sql:dump command:

--extra-dump="--column-statistics=0 --no-tablespaces"

There is no equivalent way to do this in Bee. How should we go about resolving this issue?

**Comment by yorkshire-pudding** [comment] 2022-10-05 15:18
@ElusiveMind - looking here https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109 it may be that this can be fixed by setting your server to use the mariadb version of mysqldump.

If we were to support in `bee` my preference would be for an optional argument that allows any relevant additional mysqldump / mysql arguments to be added and inserted in the right place.  This would give a flexible feature that could be used for other optional arguments.

Lando does not yet support MariaDb 10.7 (https://docs.lando.dev/mariadb/) so I can't specifically test this at the moment.

**Comment by yorkshire-pudding** [comment] 2022-10-31 18:52
@ElusiveMind - I've changed the title to reflect what I've suggested above.  I may have a go at this, though you are also welcome to.  If you do start on it, leave a note here so I don't duplicate work; I will do the same.

**Comment by yorkshire-pudding** [comment] 2022-11-08 09:35
@ElusiveMind - see PR - I've tested that it works but I don't really have any use case for this so would appreciate you testing this to ensure it meets your need.
The option is `--extra` so you would use it by typing:
`bee db-export --extra="--column-statistics=0 --no-tablespaces"`

I've only added into `db-export` as not sure if needed.  If it would be useful to have in a different command also, it would be easy enough to add it.

**Comment by ElusiveMind** [comment] 2022-11-10 01:41
@yorkshire-pudding - I should get to testing this this weekend. Sorry for the delay.  I have a deployment this week for the end of a contract, so my schedule has been tight.

**Comment by yorkshire-pudding** [comment] 2022-11-26 21:53
@ElusiveMind - any chance you can test this anytime soon?

**Comment by ElusiveMind** [comment] 2022-11-26 21:55
@yorkshire-pudding - many apologies for the shifting priorities. I'll work on testing this week. I'll update no later than Dec 2, 2022

**Comment by ElusiveMind** [comment] 2022-11-27 18:03
@yorkshire-pudding - I am still seeing issues:

```
root@a7d547f49006:/var/www/html/web/dbs# bee db-export --extra="--column-statistics=0 --no-tablespaces"
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'backdrop' AND TABLE_NAME = 'batch';': Unknown table 'column_statistics' in information_schema (1109)

 [✔] The 'backdrop' database was exported to '/var/www/html/web/20221127_175753.sql.gz'. 

root@a7d547f49006:/var/www/html/web/dbs# 
```

There is also no data being exported.

My command is being parsed as:

```
mysqldump --column-statistics --user=user --password=REDACTED --host=db backdrop | gzip > 20221127_180148.sql.gz
```

It's missing everything after the = sign on column statistics to the end of the extra.

**Comment by ElusiveMind** [comment] 2022-11-27 18:05
It seems like the root issue is how Bee is handling command line arguments and not respecting items within "'s as a single value to the argument.

**Comment by yorkshire-pudding** [comment] 2022-11-27 18:16
Can you try with single quotes and see if that works any better?

It's a long time since I did this so I can't picture what it's doing. If that doesn't work then I'll need to think of a better approach.

**Comment by ElusiveMind** [comment] 2022-11-27 18:18
No difference. If you need any assistance taking a crack at this then let me know. I don't want to get in your way, but want to be helpful

**Comment by yorkshire-pudding** [comment] 2022-11-27 18:21
Hi @ElusiveMind , please feel free to have a go. I'm not precious about this and I'm quite busy on another modules at the moment.

**Comment by yorkshire-pudding** [comment] 2022-11-27 20:23
Hi @ElusiveMind, I think this is more to do with Linux passing arguments to PHP than with `bee`.  In your use case, would it work to put in a script?  If not, you could try this one liner:
```bash
EXTRA="--column-statistics=0 --no-tablespaces";  bee db-export --extra="$EXTRA" db-export.sql
```
If a script works, just stick these on separate lines.

The alternatives would be

- to make the extra flag prompt for the extra string; I haven't tested that though. (less conducive to scripting)
- hard code this option in and call it with a suitable name,

Of course, this shouldn't be a problem if the server can use the mariadb version of mysqldump - see https://github.com/backdrop-contrib/bee/issues/208#issuecomment-1268586819

**Comment by yorkshire-pudding** [comment] 2022-11-30 18:09
@ElusiveMind
Hi Michael
Are you comfortable with the idea of using a variable to get around the bash limitation for this?  If so, I will add it into the help text, and also the Wiki, then get this merged.

**Comment by ElusiveMind** [comment] 2022-11-30 21:31
I will test it tonight. Admittedly I'm not crazy about it and would like an opportunity to have a crack at seeing if I can improve it. If I can't do it before Monday we can move forward and refine later? Will that work?

**Comment by yorkshire-pudding** [comment] 2022-11-30 21:41
Sure. If you don't come up with anything by Monday, I'll merge as is but be open to improvements in the future.

Still worth checking to see if you can switch your server to using the mariadb version of mysqldump  as that should remove the need although would probably still add it.

**Comment by ElusiveMind** [comment] 2022-12-01 12:06
I am working on this and have re-written some of the argument parsing logic. I have it working and  tested locally but I didn't get all my stuff in the first PR I submitted, so I closed it. Been up all night so I will wrap it up after some sleep.

**Comment by yorkshire-pudding** [comment] 2022-12-01 15:27
@ElusiveMind - I had a look at what you've done on the [PR that you closed](https://github.com/backdrop-contrib/bee/pull/243) and I have a few bits of feedback.

1. The PR needs to be against a ticket and it is not appropriate against this one.  First, create an enhancement ticket, something like "Accept long multi-part command line options in quotes"; second, link the PR to the ticket by putting "Fixes #issueNumber"  with issueNumber being the number of the new enhancement request.
2. Don't change things that don't need changing (i.e. don't change $opt_name to $opt_key)
3. This is quite a bit of extra complexity in the core function for something that I believe you only need as you are trying to run the MySql version of `mysqldump`  against a MariaDB database.  You haven't yet responded to my suggestion that you look at replacing with the MariaDB version - link is further up in this chain.  Unless and until you investigate that and report back, I won't be convinced that `bee` needs this.

Please report what you get when you type `mysqldump --version`.  On my hosting, which uses MariaDB, I get this:
```bash
username@host ~ $ mysqldump --version
mysqldump  Ver 10.19 Distrib 10.2.44-MariaDB, for Linux (x86_64)
```
I suspect yours will show that it is using the MySql client, which, if so, is the cause of your issue requiring these extra options.

As you're proposing to change part of the core functionality, this will need a lot of testing to ensure it doesn't break any other functions.

**Comment by ElusiveMind** [comment] 2022-12-01 15:47
Understood. We can likely just close the issue and I'll work off a patch. MariaDB 10.2 is no longer supported and this also happens under certain configurations of MySQL. It also handles a fundamental issue of multiple arguments within quoted values. I admit, it is not finished which is why I closed the PR. If it's not applicable for the greater project, I can dig that. But I will need to have it working for later MariaDB versions that are supported. As such, I can just offer up a patch that I can clean up (definitely not finished code yet. The PR I missed was premature - my apology for that). There are also occasions where other extra config options on export (max packet length, etc) sometimes are desired to be configured.

That was my impetus. I understand what your position is though.

I did try the ENV variable approach and that was not successful. I forgot to report back on that.

Thanks!

**Comment by yorkshire-pudding** [comment] 2022-12-01 15:55
I'm not saying we can't do this, just that the bar is necessarily high to justify changes to the core operation.

**Comment by ElusiveMind** [comment] 2022-12-01 15:57
Ok. I'll re-work it. I agree I did that PR prematurely. Again - my bad on that. Didn't intend for people to see it half finished. I'll clean up some today and tomorrow and revisit your requested steps and follow the rules :-D I just got excited I got it working in a poc. :)

**Comment by yorkshire-pudding** [comment] 2022-12-01 16:11
Hi @ElusiveMind - There's not a problem with putting PRs up that are not fully done; sometimes its good to get early feedback.  Indeed you can just re-open that PR and push up more commits to that branch and it will update the PR.  I think you can mark PRs as draft if they're a work in progress.  What I was saying is that what that PR does is different from what this ticket is about so it needs another ticket and to be linked to it.

**Comment by ElusiveMind** [comment] 2022-12-02 02:24
Hey @yorkshire-pudding - I made a critical mistake. My custom docker container *was* running MariaDB 10.3 or 10.6 depending on which CMS I was running, but my MySQL-client (mysqldump, mysql) was running 8.0. So that was the problem with my MySQL dump. MariaDB has no issue with the way things are in Bee. As such, my fix may not be necessary, but I wanted to offer another narrative to why we may pursue it.

1. Backdrop does support MySQL 8 and it is the default database installed on Ubuntu 20.04 and 22.04 unless you specify otherwise.
2. The adding of the extra commands fixes the parser for Bee so it can handle things like --extra="--stuff=foo --things=bar" which can be useful for some mysql related parameters. granted this is not an every day case - so it may not be seen as important enough for the scope of Bee and I'd understand that.

In either event, I will follow your guidance as to if we should pursue this or not. I can see it either way, but it would be an improvement and be more supporting of MySQL as it continues to evolve.

I welcome your thoughts. Thank you for your patience.

**Comment by yorkshire-pudding** [comment] 2022-12-02 08:02
Hi @ElusiveMind - no worries.

I totally agree that we need to support all modern MySQL versions including those that have just become EoL.  I think lots have moved to MariaDB and my host has been MariaDB for a while.

I'd be happy to put this in as-is for where people might need it and document the need to use a variable.  That may well be enough for the few cases that need this; I don't know that MySQL, set up correctly will actually need extra parameters but I can understand that some people will want to extract their Backdrop database for use in another way, and that the ability to add additional arguments might be part of that.  For edge cases, it should be enough to enter these via a variable.

However, I am also open to exploring your solution as a way to negate the need to use a variable for this function.  As I said: create a new ticket (reference this discussion) and link the PR to it.  We can then look at testing and also making sure the code is as good as it can be.

I appreciate your efforts and that you're keen to help make `bee` as good as it can be.

**Comment by yorkshire-pudding** [comment] 2022-12-05 15:22
@ElusiveMind - I've added a debug message into this export command so the compiled export command can be easily examined by adding the `--debug` flag.

**Comment by yorkshire-pudding** [comment] 2022-12-05 15:51
If the patch from PR #249 is applied first, then this should now work.

**Closed as completed** 2022-12-06 08:50 UTC
