### ISSUE TITLE
Add support for `sset` 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/b#186] opened 2022-04-27 18:58 UTC
Drupal 8+ and Backdrop both have the state system, and drush for Drupal now has a drush sset command for setting state values. I'd love to use this for backdrop as well. (It's particularly useful when working on the maintenance page)

See also https://github.com/backdrop-contrib/backdrop-drush-extension/issues/253

**Comment by ghost** [comment] 2022-04-27 20:09
Closing as a duplicate of https://github.com/backdrop-contrib/bee/issues/153

**Closed as completed by ghost** 2022-04-27 20:09 UTC
Labels: status: duplicate
